WELCOME = ('👋Hi, I\'m an inviter bot of the [MIPT Meetup](https://t.me/mipt_meetup) chat!\n\n'
           '🌎We are an international community of students and graduates of MIPT, MSU, HSE, SPbU, SDU, and other top universities\n\n'
           '🎯If you are preparing for IELTS, TOEFL, an interview with FAANG, a speech at a conference, or just don’t want to lose your speaking skill - you are welcome to join us\n')
REQUEST_WHOIS = ('📝 Could you please tell us about yourself a bit?\n'
'As we send this message in the main chat, let\'s stick with a template as below:\n\n'
'#whois\n'
'🎓facts about education\n'
'📊Work experiences\n'
'⛷ Interests/hobbies\n'
'🇬🇧Why do you want to study/practice English?\n'
'📲Social media: inst, tg channels, vk account'
)
REQUEST_ADD_WHOIS = '🏷️Please add #whois tag in your message.'
WAIT_APPROVE = '🔥Thank you, you will receive the invitation link to the chat in a while after reviewing.'
APPROVE = 'Approve'
DENY = 'Deny'
APPROVED = '🎉Congratulations, click on the link and join our community!'
DENIED = '🔁Please write the whois description in detail so that we can get to know each other better.'
