WELCOME = ('👋Hi, I\'m an invite bot of the [MIPT Meetup](https://t.me/mipt_meetup) chat!\n\n'
           '🌎We are an international community of students and graduates of MIPT, MSU, HSE, SPbU, SDU, other top universities\n\n'
           '🎯If you are preparing for IELTS, TOEFL, an interview in FAANG, a speech at a conference, or just don’t want to lose your speaking skills - you are welcome to join us\n')
REQUEST_WHOIS = ('📝 Could you tell us about yourself a bit?\n'
'As we send this message in the chat, let\'s stick with such a template:\n\n'
'#whois\n'
'🎓facts about education\n'
'📊Work experience\n'
'⛷ Interests/hobbies\n'
'🇬🇧Why do you want to study/practice English?\n'
'📲Social media: inst, tg channels, vk account'
)
REQUEST_ADD_WHOIS = '🏷️Add #whois tag to your message please'
WAIT_APPROVE = '🔥Thank you, the invite link to the chat will come soon after little review'
APPROVE = 'Approve'
DENY = 'Deny'
APPROVED = '🎉Congratulations, click on the link and join our community!'
DENIED = '🔁Please write the whois more fully and in detail so that we can get to know each other better!'