WELCOME = ('👋Hi, I\'m an invite bot of the [MIPT Meetup](https://t.me/mipt_meetup) chat!\n\n'
           '🌎We are an international community of students and graduates of top universities, people who are interested in science and technology and want to expand their network in order to move towards big goals together'
           '🎯If you are preparing for IELTS or TOEFL, an interview in FAANG, a speech at a conference, or just don’t want to lose your speaking skills - you are welcome to join us')
REQUEST_WHOIS = ('📝But before joining, tell us about yourself - about your education, work, hobbies, motivation to learn English and shere your contacts\n\n'
           '⚠️Don\'t forget add #whois tag to your message\n' 
           '🎓Institute, year of studying, field\n'
           '📊Work experience, whom would you like to become in the future\n'
           '⛷Interests / hobbies\n'
           '🇬🇧Why do you want study / practice English?\n'
           '📲Social media: inst, tg channels, vk account\n\n'
           '🔍I will send your message first to our admins for approval, and then to the general chat so that everyone can get to know you, and you can find other messages by searching for the tag #whois\n')
REQUEST_ADD_WHOIS = '🏷️Add #whois tag to your message please'
WAIT_APPROVE = '🔜Thank you, I sent a message to the admins, the approval will come soon'
APPROVE = 'Approve'
DENY = 'Deny'
APPROVED = '🎉Congratulations, click on the link and join our community!'
DENIED = '🔁Please write the whois more fully and in detail so that we can get to know each other better!'